name: Docker Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: "nixswinner"
          password: "dckr_pat_t7BbeSIXBg-wPXBgFE6oHvPGD50"
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: nixswinner/church-is:latest
